---
- hosts: kubernetes_master_node
  become_user: pratigyan 
  become: yes
  gather_facts: No
  vars_files:
  - env_variables 
  tasks:  

    - name: Copy nginx_ingress_controller_deploy.yaml with owner and permissions
      copy:
        src: nginx_ingress_controller_deploy.yaml 
        dest: $HOME/nginx_ingress_controller_deploy.yaml
        owner: pratigyan
        mode: u=rw,g=rw,o=rw

# comment this if namespace already exist
    # - name: Create ingress-nginx namespace on Cluster
    #   command: kubectl create namespace ingress-nginx

    - name: Create nginx-ingress namespace
      kubernetes.core.k8s:
        name: nginx-ingress
        api_version: v1
        kind: Namespace
        state: present

    - name: Install nginx-ingress-controller on Cluster
      command: kubectl apply -n ingress-nginx -f $HOME/nginx_ingress_controller_deploy.yaml 
      

